### ISSUE TITLE
Stonecutter email not sent when creating a new user

### ISSUE THREAD

**Issue by aspasia** [PIENews/freecoin#13]
[qtp9361871-307] WARN stonecutter.email - Cannot send confirmation email as the path to the email sending script has not been set. Please set the EMAIL_SCRIPT_PATH environment variable to the appropriate script.

**Comment by jaromil** [comment]
One of many good reasons why we will phase out stonecutter.

**Comment by aspasia** [comment]
I will close this as part of the stonecutter replacement, when it is ready.

**Comment by aspasia** [comment]
https://github.com/PIENews/freecoin/issues/27

**Comment by aspasia** [comment]
fixed by https://github.com/PIENews/freecoin/pull/33
