### ISSUE TITLE
When creating the mongo storage the transactions collection is missing

### ISSUE THREAD

**Issue by aspasia** [PIENews/freecoin#16]
https://github.com/d-cent/freecoin/commit/a3851ac2cc356a2585d191ba2dd83d549609bb3c#diff-aa48405498890086474eee655cb95fc2

**Comment by skuro** [comment]
Isn't the collection created on demand?

**Comment by aspasia** [comment]
@carlo it is. However I see the following inconsistencies:
 

1. 

I see two implementations of DB actions. The transactions are updated using https://github.com/d-cent/freecoin/blob/master/src/freecoin/storage.clj and the other two collections using FreecoinStore implementations https://github.com/d-cent/freecoin/blob/master/src/freecoin/db/mongo.clj

2. 

The other two are explicitly created and passed to the state using the create-mongo-stores https://github.com/d-cent/freecoin/blob/57694a43e285844c7c5fd6b625fa822d47fcc031/src/freecoin/db/storage.clj

3.

Tests create the stores using the Memory store https://github.com/d-cent/freecoin/blob/master/src/freecoin/db/mongo.clj. The transactions are tested using an atom.

Which makes me wonder if its in purpose or by mistake. @jaromil do you know anything about it? Is there some legacy reasons?

**Comment by skuro** [comment]
I think the original assumption was that transactions would be saved on a blockchain while other ancillary data would belong to a dedicated Freecoin storage, but @jaromil to confirm :-)

**Comment by jaromil** [comment]
It need to be made consistent, the mongodb api had some duplication and stale code indeed.

**Comment by aspasia** [comment]
Fixed by https://github.com/PIENews/freecoin/pull/29
