### ISSUE TITLE
Mover project under PiE

### ISSUE THREAD

**Issue by aspasia** [PIENews/freecoin#17]

**Comment by jaromil** [comment]
as soon as you and Carlo ACK I'll do the transfer. the remote 'origin' will change to
```
git@github.com:PIENews/freecoin
```

**Comment by skuro** [comment]
I don't have many strings attached to `d-cent`, thumbs up from my side :-)

**Comment by jaromil** [comment]
Ok but then I prefer merging #18 first, whenever you can give a greem light. Thanks!!
