### ISSUE TITLE
Missing something in my runtime

### ISSUE THREAD

**Issue by dropmeaword** [PIENews/freecoin#2]
Hi,

I installed Freecoin and Stonecutter as per the documentation (I think). I modified the Stonecutter `resources/client-credentials.yml` to include the default Freecoin sso broker credentials like so.

```
- name: Freecoin
  client-id: LOCALFREECOIN
  client-secret: FREECOINSECRET
  url: "http://localhost:8000/sso-callback"
```

When I go to the landing page in my local instance of freecoin it correctly takes me to the SSO server but then upon returning I get the following message in the freecoin log.

```
Tue Mar 01 17:07:30 CET 2016 [worker-4] ERROR - GET /sso-callback
com.mongodb.MongoServerSelectionException: Unable to connect to any servers
```

I suspect that `lein` doesn't run an instance of Mongo, yet on the _Running the app locally_ section of the readme I don't see anything about a Mongo instance. Do I need a self-standing mongodb server to be able to run Freecoin?

**Comment by arjan** [comment]
Do the tests run? `lein midje` will tell you. The tests also use mongodb.

But yes, to run a Freecoin instance you need a local mongodb installation.

**Comment by jaromil** [comment]
Yep. Not included in docs as most distros start mongo automatically on installations.
There should be a mention of it, I'll update docs on this and other matters shortly.

**Comment by skuro** [comment]
Documentation now mentions MongoDB as a required (and separately started) dependency.
