### ISSUE TITLE
Cleanup vagrant config

### ISSUE THREAD

**Issue by aspasia** [PIENews/freecoin#31]
have not been tested for some time. Removed stonecutter and maybe more that still there

**Comment by Radiumgit** [comment]
Thanks

On 26 April 2017 23:40:43 BST, Jaromil <notifications@github.com> wrote:
>Closed #31 via 7da153d7e03f3f0aa720a5afe8f6fea727f1a21b.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PIENews/freecoin/issues/31#event-1059503709

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
