### ISSUE TITLE
Forgot password functionality

### ISSUE THREAD

**Issue by jaromil** [PIENews/freecoin#47]
Some small problems spotted:

- [x] resend works with any email address, also already activated accounts
- [ ] there is no way to reset the password for those who forgot it

**Comment by aspasia** [comment]
For the first I thought about it and it doesnt matter actually. The only thing that the activation does is to set inactive to active. If an account is already active then nothing changes. You cannot resend the activation link to someone not signed up.

For the second that's another story I think. I thought we want to think of a recovery strategy. Using secrets? Some other way? But I agree it will be a problem.
