### ISSUE TITLE
Bad getaway error after sign up

### ISSUE THREAD

**Issue by aspasia** [PIENews/freecoin#55]
Something goes wrong with the redirect

**Comment by aspasia** [comment]
The email is sent so usable for now

**Comment by jaromil** [comment]
referred in #58 along with other registration glitches

**Comment by aspasia** [comment]
Why we need this as duplicate?

**Comment by aspasia** [comment]
The error was 2017/06/20 14:55:42 [error] 25733#0: *6492 upstream sent too big header while reading response header from upstream, client: 82.161.183.216, server: freecoin1staging.dyne.org, request: "POST /reset-password/aspra@dyne.org/JDcBipCNC1tKfVFRiQu1s1CMsocpu9ig HTTP/1.1", upstream: "http://127.0.0.1:8000/reset-password/aspra@dyne.org/JDcBipCNC1tKfVFRiQu1s1CMsocpu9ig", host: "freecoin1staging.dyne.org",
16:55 referrer: "https://freecoin1staging.dyne.org/reset-password/aspra@dyne.org/JDcBipCNC1tKfVFRiQu1s1CMsocpu9ig"

We changed the settings of proxy_busy_buffers_size @ /etc/nginx/sites-enabled/default -  the cookie was bigger than the proxy setting.
