### ISSUE TITLE
Glitches in the account registration journey

### ISSUE THREAD

**Issue by jaromil** [PIENews/freecoin#58]
When **registering** a new account there are small glitches to be addressed:

- [ ] when connecting on the home page there is no obvious link to landing-page
- [ ] when password is wrong there is a reload with error but valid data is not kept in the form
- [x] when succesfully registered there is a broken route (we get error from nginx) (see figure 1 below)
- [ ] error appears above all forms (addressed in #44)

![Figure 1](https://transfer.sh/u6NUQ/latest-screenshot.png)

**Comment by aspasia** [comment]
Most of the above are already addressed in different issues:
4th-> #44 
3rd-> #55   
1st -> I added it to #41 

I suggest we keep them separate as they are
