### ISSUE TITLE
Tagging system for transactions

### ISSUE THREAD

**Issue by jaromil** [PIENews/freecoin#6]
To quickly navigate transactions in relation to projects, we need tagging in their description.

I'm investigating what is the best DB tech to adopt for small/medium scale of tagging on the long term, perhaps reverting to SQL is best. In that case an approach made of 3 tables would be best:

```
ENTRIES - the things being tagged
ent_id (IDX)
other columns as needed

TAGS
tag_id
tag_name (IDX)
created_by
created_when

ENTRY_TAGS
et_id
ent_id (IDX)
tag_id (IDX)
start/end date if tags can be added or removed after the original entry
```

or have also a reference table linking users to tags they use

```
Items
ItemID

ItemTags
ItemID (IDX)
TagID (IDX)

Tags
TagID

UserTags
ItemID (IDX)
UserID (IDX)
```

**Comment by skuro** [comment]
In principle, it should be possible to embed tags in transaction documents:

```js
{
   transaction_id: '1234567890-aaabbb',
   blockchain: 'WHATEVER',
   timestamp: 1234567890,
   from_id: 'aaabbb',
   to_id: 'bbbaaa',
   amount: 42,
   tags: ['donation', 'freecoin'] // <-- new field
}
```
then keep extra metadata, if needed, on the tag itself in a dedicated document (reusing your schema for their metas):

```js
{
   tagname: 'donation',
   created_by: 'skuro',
   created_when: 1234567890
}
```

This can of course present many data anomalies, both in read and write, but that's NoSQL. It might be wise to try to foresee what use cases will make use of tagging before designing the data layer. Off the top of my head:

- basic CRUD of tags per transaction
- find all tags associated to the current user (i.e. found in at least one transaction in which user is in the `from` or `to` or either fields)
- search transactions for a given tag
- retrieve statistics on tags usage

Anything else?

On the tags metadata, I'm not sure what the usefulness of `created_by` and `created_when` would be.

**Comment by jaromil** [comment]
Use cases:
- CRUD of tags on transaction creation (no edit)
- find all tags associated with user
- find all users associated with tag
- search all transactions with tag, optionally ranging from date to date
- calculate volume (sum of all value moved) of transactions associated with tag (date range optional)

I thought of using an array as collection field, but then how practical is to run a search? Wouldn't this add a lot of overhead? Perhaps the tag metadata should also have an array of all transactions having the tag...
BTW the date range is necessary also for pruning, to avoid infinite growth of this sort of metadata.

**Comment by codeflyer** [comment]
With mongodb you can query directly on an array filed in the same way you do it for a string.


To search all the user with a specific tag:
```
NameOfTheCollection.find({tags: 'donation'})
```

To do fast search an index should be added in the collection for the field `tags`:
```
NameOfTheCollection.createIndex({tags: 1})
```

To do all the other operations, you should use the aggregation framework or the map/reduce.

**Comment by skuro** [comment]
In order to track progress, here's the list of features to implement:

- [x] CRUD of tags on transaction creation (no edit)
- [x] find all tags associated with user
- [ ] find all users associated with tag
- [x] search all transactions with tag
- [ ] optionally ranging from date to date (nice to have)
- [ ] calculate volume (sum of all value moved) of transactions associated with tag (date range optional)

**Comment by aspasia** [comment]
This should be solving the metadata part that was left for this story. @skuro can you please have a look?
